# Generated by Django 6.0 on 2025-12-11 21:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artist', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='song',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='artist.artist'),
        ),
        migrations.AddField(
            model_name='songpurchase',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='song_purchases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='songpurchase',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='artist.song'),
        ),
        migrations.AddIndex(
            model_name='song',
            index=models.Index(fields=['artist'], name='artist_song_artist__b4db2c_idx'),
        ),
    ]
